const std::map<uint32_t, std::string> vxdNames = {
    { 0x0001, "VMM" },
    { 0x0002, "DEBUG" },
    { 0x0003, "VPICD" },
    { 0x0004, "VDMAD" },
    { 0x0005, "VTD" },
    { 0x0006, "V86MMGR" },
    { 0x0007, "PageSwap" },
    { 0x0009, "REBOOT" },
    { 0x000A, "VDD" },
    { 0x000B, "VSD" },
    { 0x000C, "VMD / VMOUSE" },
    { 0x000D, "VKD" },
    { 0x000E, "VCD" },
    { 0x0010, "BlockDev / IOS" },
    { 0x0011, "VMCPD" },
    { 0x0012, "EBIOS" },
    { 0x0014, "VNETBIOS" },
    { 0x0015, "DOSMGR" },
    { 0x0017, "SHELL" },
    { 0x0018, "VMPoll" },
    { 0x001A, "DOSNET" },
    { 0x001B, "VFD" },
    { 0x001C, "LoadHi" },
    { 0x0020, "Int13" },
    { 0x0021, "PAGEFILE" },
    { 0x0026, "VPOWERD" },
    { 0x0027, "VXDLDR" },
    { 0x0028, "NDIS" },
    { 0x002A, "VWIN32" },
    { 0x002B, "VCOMM" },
    { 0x002C, "SPOOLER" },
    { 0x0032, "VSERVER" },
    { 0x0033, "CONFIGMG" },
    { 0x0034, "DWCFGMG.SYS" },
    { 0x0036, "VFBACKUP" },
    { 0x0037, "VMINI / ENABLE" },
    { 0x0038, "VCOND" },
    { 0x003D, "BIOS" },
    { 0x003E, "WSOCK" },
    { 0x0040, "IFSMgr" },
    { 0x0041, "VCDFSD" },
};

const char* const VmmServiceIds[0x192] = {
    "get version",
    "get current VM handle",
    "test current VM handle",
    "get system VM handle",
    "test system VM handle",
    "validate VM handle",
    "get VMM reenter count",
    "begin reentrant execution",
    "end reentrant execution",
    "install V86 breakpoint",
    "remove V86 breakpoint",
    "allocate V86 callback",
    "allocation PM callback",
    "call when VM returns",
    "schedule global event",
    "schedule VM event",
    "call global event",
    "call VM event",
    "cancel global event",
    "cancel VM event",
    "call priority VM event",
    "cancel priority VM event",
    "get NMI handler address",
    "set NMI handler address",
    "hook NMI event",
    "call when VM interrupts enabled",
    "enable VM interrupts",
    "disable VM interrupts",
    "map flat",
    "map linear to VM address",
    "adjust execution priority",
    "begin critical section",
    "end critical section",
    "end critical section and suspend",
    "claim critical section",
    "release critical section",
    "call when not critical",
    "create semaphore",
    "destroy semaphore",
    "wait on semaphore",
    "signal semaphore",
    "get critical section status",
    "call when task switched",
    "suspend VM",
    "resume VM",
    "no-fail resume VM",
    "nuke VM",
    "crash current VM",
    "get execution focus",
    "set execution focus",
    "get time slice priority",
    "set time slice priority",
    "get time slice granularity",
    "set time slice granularity",
    "get time slice information",
    "adjust execution time",
    "release time slice",
    "wake up VM",
    "call when idle",
    "get next VM handle",
    "set global timeout",
    "set VM timeout",
    "cancel timeout",
    "get system time",
    "get VM execution time",
    "hook V86 interrupt chain",
    "get V86 interrupt vector",
    "set V86 interrupt vector",
    "get PM interrupt vector",
    "set PM interrupt vector",
    "simulate interrupt",
    "simulate IRET",
    "simulate far call",
    "simulate far jump",
    "simulate far RET",
    "simulate far RET N",
    "build interrupt stack frame",
    "simulate push",
    "simulate pop",
    "_HeapAllocate",
    "_HeapReAllocate",
    "_HeapFree",
    "_HeapGetSize",
    "_PageAllocate",
    "_PageReAllocate",
    "_PageFree",
    "_PageLock",
    "_PageUnLock",
    "_PageGetSizeAddr",
    "_PageGetAllocInfo",
    "_GetFreePageCount",
    "_GetSysPageCount",
    "_GetVMPgCount",
    "_MapIntoV86",
    "_PhysIntoV86",
    "_TestGlobalV86Mem",
    "_ModifyPageBits",
    "copy page table",
    "map linear into V86",
    "linear page lock",
    "linear page unlock",
    "_SetResetV86Pageabl",
    "_GetV86PageableArray",
    "_PageCheckLinRange",
    "page out dirty pages",
    "discard pages",
    "_GetNulPageHandle",
    "get first V86 page",
    "map physical address to linear address",
    "_GetAppFlatDSAlias",
    "_SelectorMapFlat",
    "_GetDemandPageInfo",
    "_GetSetPageOutCount",
    "hook V86 page",
    "assign device V86 pages",
    "deassign device V86 pages",
    "get array of V86 pages for device",
    "_SetNULPageAddr",
    "allocate GDT selector",
    "free GDT selector",
    "allocate LDT selector",
    "free LDT selector",
    "_BuildDescriptorDWORDs",
    "get descriptor",
    "set descriptor",
    "toggle HMA",
    "get fault hook addresses",
    "hook V86 fault",
    "hook PM fault",
    "hook VMM fault",
    "begin nested V86 execution",
    "begin nested execution",
    "execute V86-mode interrupt",
    "resume execution",
    "end nested execution",
    "allocate PM application callback area",
    "get current PM application callback area",
    "set V86 execution mode",
    "set PM execution mode",
    "begin using locked PM stack",
    "end using locked PM stack",
    "save client state",
    "restore client state",
    "execute VxD interrupt",
    "hook device service",
    "hook device V86 API",
    "hook device PM API",
    "system control (see also #02657)",
    "simulate I/O",
    "install multiple I/O handlers",
    "install I/O handler",
    "enable global trapping",
    "enable local trapping",
    "disable global trapping",
    "disable local trapping",
    "create list",
    "destroy list",
    "allocate list",
    "attach list",
    "attach list tail",
    "insert into list",
    "remove from list",
    "deallocate list",
    "get first item in list",
    "get next item in list",
    "remove first item in list",
    "add instance item",
    "allocate device callback area",
    "allocate global V86 data area",
    "allocate temporary V86 data area",
    "free temporary V86 data area",
    "get decimal integer from profile",
    "convert decimal string to integer",
    "get fixed-point number from profile",
    "convert fixed-point string",
    "get hex integer from profile",
    "convert hex string to integer",
    "get boolean value from profile",
    "convert boolean string",
    "get string from profile",
    "get next string from profile",
    "get environment string",
    "get exec path",
    "get configuration directory",
    "open file",
    "get PSP segment",
    "get DOS vectors",
    "get machine information",
    "get/set HMA information",
    "set system exit code",
    "fatal error handler",
    "fatal memory error",
    "update system clock",
    "test if debugger installed",
    "output debugger string",
    "output debugger character",
    "input debugger character",
    "debugger convert hex to binary",
    "debugger convert hex to decimal",
    "debugger test if valid handle",
    "validate client pointer",
    "test reentry",
    "queue debugger string",
    "log procedure call",
    "debugger test current VM",
    "get PM interrupt type",
    "set PM interrupt type",
    "get last updated system time",
    "get last updated VM execution time",
    "test if double-byte character-set lead byte",
    "_AddFreePhysPage",
    "_PageResetHandlePAddr",
    "_SetLastV86Page",
    "_GetLastV86Page",
    "_MapFreePhysReg",
    "_UnmapFreePhysReg",
    "_XchgFreePhysReg",
    "_SetFreePhysRegCalBk",
    "get next arena (MCB)",
    "get name of ugly TSR",
    "get debug options",
    "set physical HMA alias",
    "_GetGlblRng0V86IntBase",
    "add global V86 data area",
    "get/set detailed VM error",
    "Is_Debug_Chr",
    "clear monochrome screen",
    "output character to mono screen",
    "output string to mono screen",
    "set current position on mono screen",
    "get current position on mono screen",
    "get character from mono screen",
    "locate byte in ROM",
    "hook invalid page fault",
    "unhook invalid page fault",
    "set delete on exit file",
    "close VM",
    "Enable_Touch_1st_Meg",
    "Disable_Touch_1st_Meg",
    "install exception handler",
    "remove exception handler",
    "Get_Crit_Status_No_Block",
    "_Schedule_VM_RTI_Event",
    "_Trace_Out_Service",
    "_Debug_Out_Service",
    "_Debug_Flags_Service",
    "VMM add import module name",
    "VMM Add DDB",
    "VMM Remove DDB",
    "get thread time slice priority",
    "set thread time slice priority",
    "schedule thread event",
    "cancel thread event",
    "set thread timeout",
    "set asynchronous timeout",
    "_AllocatreThreadDataSlot",
    "_FreeThreadDataSlot",
    "create Mutex",
    "destroy Mutex",
    "get Mutex owner",
    "call when thread switched",
    "create thread",
    "start thread",
    "terminate thread",
    "get current thread handle",
    "test current thread handle",
    "Get_Sys_Thread_Handle",
    "Test_Sys_Thread_Handle",
    "Validate_Thread_Handle",
    "Get_Initial_Thread_Handle",
    "Test_Initial_Thread_Handle",
    "Debug_Test_Valid_Thread_Handle",
    "Debug_Test_Cur_Thread",
    "VMM_GetSystemInitState",
    "Cancel_Call_When_Thread_Switched",
    "Get_Next_Thread_Handle",
    "Adjust_Thread_Exec_Priority",
    "_Deallocate_Device_CB_Area",
    "Remove_IO_Handler",
    "Remove_Mult_IO_Handlers",
    "unhook V86 interrupt chain",
    "unhook V86 fault handler",
    "unhook PM fault handler",
    "unhook VMM fault handler",
    "unhook device service",
    "_PageReserve",
    "_PageCommit",
    "_PageDecommit",
    "_PagerRegister",
    "_PagerQuery",
    "_PagerDeregister",
    "_ContextCreate",
    "_ContextDestroy",
    "_PageAttach",
    "_PageFlush",
    "_SignalID",
    "_PageCommitPhys",
    "_Register_Win32_Services",
    "Cancel_Call_When_Not_Critical",
    "Cancel_Call_When_Idle",
    "Cancel_Call_When_Task_Switched",
    "_Debug_Printf_Service",
    "enter Mutex",
    "leave Mutex",
    "simulate VM I/O",
    "Signal_Semaphore_No_Switch",
    "_MMSwitchContext",
    "_MMModifyPermissions",
    "_MMQuery",
    "_EnterMustComplete",
    "_LeaveMustComplete",
    "_ResumeExecMustComplete",
    "get thread termination status",
    "_GetInstanceInfo",
    "_ExecIntMustComplete",
    "_ExecVxDIntMustComplete",
    "begin V86 serialization",
    "unhook V86 page",
    "VMM_GetVxDLocationList",
    "VMM_GetDDBList get start of VxD chain",
    "unhook NMI event",
    "Get_Instanced_V86_Int_Vector",
    "get or set real DOS PSP",
    "call priority thread event",
    "Get_System_Time_Address",
    "Get_Crit_Status_Thread",
    "Get_DDB",
    "Directed_Sys_Control",
    "_RegOpenKey",
    "_RegCloseKey",
    "_RegCreateKey",
    "_RegDeleteKey",
    "_RegEnumKey",
    "_RegQueryValue",
    "_RegSetValue",
    "_RegDeleteValue",
    "_RegEnumValue",
    "_RegQueryValueEx",
    "_RegSetValueEx",
    "_CallRing3",
    "Exec_PM_Int",
    "_RegFlushKey",
    "_PageCommitContig",
    "_GetCurrentContext",
    "_LocalizeSprintf",
    "_LocalizeStackSprintf",
    "Call_Restricted_Event",
    "Cancel_Restricted_Event",
    "Register_PEF_Provider",
    "_GetPhysPageInfo",
    "_RegQueryInfoKey",
    "MemArb_Reserve_Pages",
    "Time_Slice_Sys_VM_Idle",
    "Time_Slice_Sleep",
    "Boost_With_Decay",
    "Set_Inversion_Pri",
    "Reset_Inversion_Pri",
    "Release_Inversion_Pri",
    "Get_Thread_Win32_Pri",
    "Set_Thread_Win32_Pri",
    "Set_Thread_Static_Boost",
    "Set_VM_Static_Boost",
    "Release_Inversion_Pri_ID",
    "Attach_Thread_To_Group",
    "Detach_Thread_From_Group",
    "Set_Group_Static_Boost",
    "_GetRegistryPath",
    "_GetRegistryKey",
    "_CleanupNestedExec",
    "_RegRemapPreDefKey",
    "End_V86_Serialization",
    "_Assert_Range",
    "_Sprintf",
    "_PageChangePager",
    "_RegCreateDynKey",
    "RegQMulti",
    "Boost_Thread_With_VM",
    "Get_Boot_Flags",
    "Set_Boot_Flags",
    "_lstrcpyn",
    "_lstrlen",
    "_lmemcpy",
    "_GetVxDName",
    "Force_Mutexes_Free",
    "Restore_Forced_Mutexes",
    "_AddReclaimableItem",
    "_SetReclaimableItem",
    "_EnumReclaimableItem",
    "Time_Slice_Wake_Sys_VM",
    "VMM_Replace_Global_Environment",
    "Begin_Non_Serial_Nest_V86_Exec",
    "Get_Nest_Exec_Status",
    "Open_Boot_Log",
    "Write_Boot_Log",
    "Close_Boot_Log",
    "EnableDisable_Boot_Log",
    "_Call_On_My_Stack",
    "Get_Inst_V86_Int_Vec_Base",
    "_lstrcmpi",
    "_strupr",
    "Log_Fault_Call_Out",
    "_AtEventTime",
};
